database:
  host: localhost
  database: Skyblock
  username: username
  password: password
  port: 3306

# Server communication (proxy <-> server)
communication:
  # Available types: Bungee, Redis
  type: Bungee

  # Specific to Redis

  # host: localhost
  # port: 6379
  # password: password

  # Specific to Bungee

  # PLEASE CHANGE THIS TO SOMETHING UNIQUE, OTHERWISE PEOPLE WILL BE ABLE TO SPY INTO SOME ISLAND DATA
  channel: skyblock:communication


redis:
  enable: false # Set to true if using multiple proxies

  host: localhost
  port: 0 # Set to 0 or remove this line for default port
  password: "" # Set empty or remove this line for no password