# General island settings
island:

  # The spawn point of the island
  spawn-location:
    x: 256
    y: 128
    z: 256

  # Available choices:
  # FAWE - Uses FastAsyncWorldEdit to paste in the island
  # DEFAULT - Unloads the world, sets the region file and reloads
  # If you're using SlimeWorldManager, I suggest you go with DEFAULT
  pasting-type: DEFAULT
  # Max number of loaded islands at once
  # Worlds will be loaded and cleaned on demand
  island-worlds: 25
  # Overworld settings
  overworld:
    # The max island size, used for storage
    max-size: 500
    # The inicial size of the island, used for upgrades
    inicial-size: 100

    # The settings that will be applicable to each island
    settings:
      allow-fire: true
      creeper-explosion-block-damage: true
      creeper-explosion-damage: true
      tnt-explosion-block-damage: true
      tnt-explosion-damage: true
      wither-explosion-block-damage: true
      wither-explosion-damage: true
      natural-mobs: true
      enderman-grief: true
      enderman-drop-block: true


  nether:
    # The nether worlds can be disabled, not yet implemented, beware
    enabled: false

# If the player should respawn in their spawn point, otherwise defaults to the server's spawn point
island-respawn-on-death: true

# For a more Hypixel Skyblock experience, players won't appear in TAB or in the game, other islands won't be rendered if set to false
show-other-players: false



