database:
  # Available types: MySQL, MONGODB, FILE, S3, SQLITE
  type: SQLITE

  # MYSQL -
  host: localhost
  database: Skyblock
  username: username
  password: password
  port: 3306

  # MONGODB -
  # ip: localhost
  # database: Skyblock
  # port: 27017

  # FILE - <EMPTY>
  # SQLITE - <EMPTY>

  # S3 -
  # bucket: bucket-name
  # region: region-name
  # access-key: access-key
  # secret-key: secret-key


# ------------------------------------------------------------------------------
# This block only applies if you're using a bungee server.
# This block will be ignored if you're not using a bungee server.
# The database connection must be the same as all the proxies you're using,
# or you will get an error.

communication:
  # Available types: Redis
  type: Redis

  # Specific to Redis

  host: localhost
  port: 6379
  password: password

  # This value must correspond to the server name in the BungeeCord config.
  server-id: "skyblock"

# ------------------------------------------------------------------------------


delay: # All delays in ticks

  # Delay between saving the world, and obtaining the saved data
  # On spigot servers, this can be lower. PaperSpigot does async IO,
  # without a way to tell if the IO is done, so we wait a pre-defined delay.

  # If you're having issues where data is not being properly saved, increase this delay.
  # If the server is not releasing islands quick enough, lower this delay.
  after-save: 4

  # Delay between unloading the island world, and allowing the world to be re-used
  # Some servers experience corrupted data when reloading worlds too fast, so increase
  # this delay if you're experiencing corruption issues when people join and leave too often.
  release-world: 200

  # Delay between starting a world load, and recognizing it as loaded.
  # On 1.18+ servers, this can be a lifesaver.
  world-load: 5